name: pharmastock_manager
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  universal_html: ^2.2.4
  mobile_scanner: ^7.0.1
  supabase_flutter: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl_phone_field: ^3.2.0
dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # 🚨 CRITICAL: Required for code quality - DO NOT REMOVE
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
    - assets/env.json
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES
